robot:
  name: kbot_arm
can:
  interface: can0
  bitrate: 1000000
control:
  rate_hz: 100
  default_kp: 20.0
  default_kd: 2.0
joints:
  shoulder_pitch:
    motor_id: 21
    min: -92.3
    max: 222.4
    max_torque: 40
    sign: 1
    zero_offset: 171.22
  shoulder_roll:
    motor_id: 22
    min: -176.1
    max: 12.7
    max_torque: 40
    sign: -1
    zero_offset: -12.69
  elbow:
    motor_id: 23
    min: -2.4
    max: 177.4
    max_torque: 20
    sign: 1
    zero_offset: -170.37
  wrist_pitch:
    motor_id: 24
    min: -2.4
    max: 8.7
    max_torque: 6
    sign: 1
    zero_offset: 280.26
  wrist_roll:
    motor_id: 25
    min: -108.1
    max: -0.1
    max_torque: 6
    sign: 1
    zero_offset: 108.13
safety:
  watchdog_timeout_ms: 50
  max_temperature: 70
